# Fallback palette for Hyprlock. Matugen overwrites this file.
$background = rgba(0f1416ff)
$on_secondary_container = rgba(cee6f0ff)
$on_surface_variant = rgba(bfc8ccff)
$secondary = rgba(b3cad3ff)
$source_color = rgba(0e3c48ff)
